title: "Reconhecimento de Placas - Documentação"
description: "Documentação completa do sistema de visão computacional para detecção e OCR de placas de veículos e sinais de trânsito"
version: "2.0.0"
last_updated: "2024-01-15"
maintainers:
  - name: "Equipe de Desenvolvimento"
    email: "dev@empresa.com"

theme: jekyll-theme-cayman
show_downloads: false

url: "https://amarorn.github.io/reconhecimento-de-placas"
baseurl: "/reconhecimento-de-placas"

nav:
  - title: "Início"
    url: "/"
  - title: "Início Rápido"
    url: "/getting-started/quick-start"
  - title: "Arquitetura"
    url: "/architecture/overview"
  - title: "API Reference"
    url: "/api-reference/endpoints"

search: true
search_full_content: true

google_analytics: false

comments: false

social:
  github: amarorn
  twitter: false
  linkedin: false

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

collections:
  docs:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "page"
      author: "Equipe de Desenvolvimento"
      comments: false
      share: false
