name: CI/CD Pipeline - Visão Computacional

on:
  push:
    branches: [ main, refactor-vision-architecture, develop ]
  pull_request:
    branches: [ main, refactor-vision-architecture ]

env:
  PYTHON_VERSION: '3.9'
  PIP_CACHE_DIR: ~/.cache/pip

jobs:
  test:
    name: Testes e Qualidade de Código
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10']
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      
    - name: Configurar Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        
    - name: Instalar dependências do sistema
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-glx libglib2.0-0 libsm6 libxext6 libxrender-dev
        sudo apt-get install -y tesseract-ocr tesseract-ocr-por
        
    - name: Instalar dependências Python
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_refatorado.txt
        pip install pytest pytest-cov pytest-asyncio
        pip install black flake8 mypy
        
    - name: Verificar formatação com Black
      run: |
        black --check --diff vision/ config/ tests/ examples/
        
    - name: Verificar estilo com Flake8
      run: |
        flake8 vision/ config/ tests/ examples/ --max-line-length=100 --ignore=E203,W503
        
    - name: Verificar tipos com MyPy
      run: |
        mypy vision/ config/ --ignore-missing-imports --no-strict-optional
        
    - name: Executar testes unitários
      run: |
        pytest tests/test_preprocessing.py tests/test_detection.py tests/test_ocr.py -v --cov=vision --cov-report=term-missing
        
    - name: Executar testes de integração
      run: |
        pytest tests/test_pipeline.py tests/test_integration.py -v --cov=vision --cov-report=term-missing
        
    - name: Gerar relatório de cobertura
      run: |
        pytest --cov=vision --cov=config --cov-report=html:htmlcov --cov-report=xml
        
    - name: Upload cobertura para Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        
  build:
    name: Build e Teste de Imagem
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      
    - name: Configurar Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build imagem Docker
      run: |
        docker build -t vision-pipeline:test .
        
    - name: Testar imagem Docker
      run: |
        docker run --rm vision-pipeline:test python -c "import vision; print('✅ Build bem-sucedido')"
        
  security:
    name: Análise de Segurança
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Instalar dependências
      run: |
        pip install bandit safety
        
    - name: Análise de segurança com Bandit
      run: |
        bandit -r vision/ config/ -f json -o bandit-report.json || true
        
    - name: Verificar vulnerabilidades de dependências
      run: |
        safety check --json --output safety-report.json || true
        
    - name: Upload relatórios de segurança
      uses: actions/upload-artifact@v3
      with:
        name: security-reports
        path: |
          bandit-report.json
          safety-report.json
          
  performance:
    name: Testes de Performance
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Instalar dependências
      run: |
        pip install -r requirements_refatorado.txt
        pip install pytest-benchmark
        
    - name: Executar benchmarks
      run: |
        pytest tests/ --benchmark-only --benchmark-skip --benchmark-min-rounds=5
        
  deploy-staging:
    name: Deploy para Staging
    runs-on: ubuntu-latest
    needs: [test, build, security]
    if: github.ref == 'refs/heads/develop'
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      
    - name: Deploy para ambiente de staging
      run: |
        echo "🚀 Deployando para staging..."
        # Aqui você pode adicionar comandos para deploy real
        # Por exemplo: kubectl apply, docker push, etc.
        
  deploy-production:
    name: Deploy para Produção
    runs-on: ubuntu-latest
    needs: [test, build, security]
    if: github.ref == 'refs/heads/main'
    environment: production
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      
    - name: Deploy para produção
      run: |
        echo "🚀 Deployando para produção..."
        # Aqui você pode adicionar comandos para deploy real
        # Por exemplo: kubectl apply, docker push, etc.

  notify:
    name: Notificações
    runs-on: ubuntu-latest
    needs: [test, build, security, performance]
    if: always()
    
    steps:
    - name: Notificar resultado
      run: |
        if [ "${{ needs.test.result }}" == "success" ] && [ "${{ needs.build.result }}" == "success" ]; then
          echo "✅ Pipeline executado com sucesso!"
        else
          echo "❌ Pipeline falhou!"
          exit 1
        fi